<?php

use App\Models\Location;
use App\Models\Shipment;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\UploadedFile;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Spatie\Permission\Models\Role;

beforeEach(function (): void {
    Role::create(['name' => 'administrator']);
});

it('imports a Rittal PBI spreadsheet using the alternate header mapping', function (): void {
    $admin = User::factory()->create();
    $admin->assignRole('administrator');

    $oldPickup = Location::factory()->pickup()->create(['short_code' => 'OLDP', 'name' => 'Old Pickup']);
    $oldDc = Location::factory()->distribution_center()->create(['short_code' => 'OLDD', 'name' => 'Old DC']);
    $newPickup = Location::factory()->pickup()->create(['short_code' => 'ING', 'name' => 'Ingrasys']);
    $newDc = Location::factory()->distribution_center()->create([
        'short_code' => 'AMS',
        'name' => 'AMS DC',
        'expected_arrival_time' => '08:00:00',
    ]);

    $shipment = Shipment::query()->create([
        'guid' => (string) str()->uuid(),
        'shipment_number' => 'LOAD-200',
        'status' => 'Pending',
        'po_number' => 'PO-100',
        'pickup_location_id' => $oldPickup->id,
        'dc_location_id' => $oldDc->id,
        'rack_qty' => 1,
        'load_bar_qty' => 1,
        'strap_qty' => 1,
    ]);

    $response = $this->actingAs($admin)
        ->from(route('admin.shipments.index'))
        ->post(route('admin.shipments.pbi-import'), [
            'file' => createPbiSpreadsheetUpload([
                ['Generated by Rittal Power BI'],
                ['Reporting period: March 2026'],
                ['Load', 'Status', 'Pro #', 'Order #', 'PickupRefNum', 'Origin', 'OriginAddress', 'OriginState', 'Destination', 'DestAddress', 'DestState', 'Sum of Pallets', 'Ship Date', 'Deliver Date', 'FETA'],
                ['LOAD-200', 'In Transit', 'PRO-9', 'PO-222', 'PICK-1', 'ING', '123 Origin St', 'TX', 'AMS', '456 Dest St', 'CA', 5, '3/26/2026', '3/27/2026', '3/27/2026'],
            ]),
        ]);

    $response->assertRedirect(route('admin.shipments.index'));
    $response->assertSessionHas('success', '0 new shipment(s) imported, 1 existing updated.');

    expect($shipment->fresh())
        ->status->toBe('In Transit')
        ->po_number->toBe('PO-222')
        ->pickup_location_id->toBe($newPickup->id)
        ->dc_location_id->toBe($newDc->id)
        ->rack_qty->toBe(5)
        ->load_bar_qty->toBe(2)
        ->strap_qty->toBe(13)
        ->pickup_date->format('Y-m-d H:i:s')->toBe(Carbon::parse('2026-03-26 08:00:00')->toDateTimeString())
        ->delivery_date->format('Y-m-d H:i:s')->toBe(Carbon::parse('2026-03-27 08:00:00')->toDateTimeString());

    expect($shipment->notes()->where('content', 'like', 'PBI import updated this shipment:%')->exists())->toBeTrue();
});

it('normalizes checked-in status from pbi import', function (): void {
    $admin = User::factory()->create();
    $admin->assignRole('administrator');

    $pickup = Location::factory()->pickup()->create(['short_code' => 'ING', 'name' => 'Ingrasys']);
    $dc = Location::factory()->distribution_center()->create(['short_code' => 'AMS', 'name' => 'AMS DC']);

    $shipment = Shipment::query()->create([
        'guid' => (string) str()->uuid(),
        'shipment_number' => 'LOAD-201',
        'status' => 'Pending',
        'pickup_location_id' => $pickup->id,
        'dc_location_id' => $dc->id,
    ]);

    $response = $this->actingAs($admin)
        ->from(route('admin.shipments.index'))
        ->post(route('admin.shipments.pbi-import'), [
            'file' => createPbiSpreadsheetUpload([
                ['Generated by Rittal Power BI'],
                ['Reporting period: March 2026'],
                ['Load', 'Status', 'Order #', 'Origin', 'Destination', 'Sum of Pallets', 'Ship Date'],
                ['LOAD-201', 'Checked-In', 'PO-201', 'ING', 'AMS', 1, '3/26/2026'],
            ]),
        ]);

    $response->assertRedirect(route('admin.shipments.index'));

    expect($shipment->fresh())
        ->status->toBe('Checked In');
});

it('skips pbi updates for fields previously changed by google sheets import notes', function (): void {
    $admin = User::factory()->create();
    $admin->assignRole('administrator');

    $pickup = Location::factory()->pickup()->create(['short_code' => 'ING', 'name' => 'Ingrasys']);
    $dc = Location::factory()->distribution_center()->create(['short_code' => 'AMS', 'name' => 'AMS DC']);

    $shipment = Shipment::query()->create([
        'guid' => (string) str()->uuid(),
        'shipment_number' => 'LOAD-202',
        'status' => 'Pending',
        'po_number' => 'PO-OLD',
        'pickup_location_id' => $pickup->id,
        'dc_location_id' => $dc->id,
        'rack_qty' => 1,
        'load_bar_qty' => 1,
        'strap_qty' => 1,
    ]);

    $shipment->notes()->create([
        'content' => "Google Sheets import updated this shipment:\nStatus changed from 'Booked' to 'Pending'",
        'is_admin' => false,
        'user_id' => $admin->id,
    ]);

    $response = $this->actingAs($admin)
        ->from(route('admin.shipments.index'))
        ->post(route('admin.shipments.pbi-import'), [
            'file' => createPbiSpreadsheetUpload([
                ['Generated by Rittal Power BI'],
                ['Reporting period: March 2026'],
                ['Load', 'Status', 'Order #', 'Origin', 'Destination', 'Sum of Pallets', 'Ship Date'],
                ['LOAD-202', 'In Transit', 'PO-NEW', 'ING', 'AMS', 1, '3/26/2026'],
            ]),
        ]);

    $response->assertRedirect(route('admin.shipments.index'));

    expect($shipment->fresh())
        ->status->toBe('Pending')
        ->po_number->toBe('PO-NEW');
});

function createPbiSpreadsheetUpload(array $rows): UploadedFile
{
    $spreadsheet = new Spreadsheet;
    $spreadsheet->getActiveSheet()->fromArray($rows, null, 'A1');

    $path = tempnam(sys_get_temp_dir(), 'pbi-import-');

    if ($path === false) {
        throw new RuntimeException('Failed to allocate a temporary file for the PBI import test.');
    }

    $writer = new Xlsx($spreadsheet);
    $writer->save($path);

    return new UploadedFile(
        $path,
        'rittal-pbi.xlsx',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        null,
        true,
    );
}
