<?php

use App\Mail\ImportSummaryEmail;
use App\Models\Location;
use App\Models\Notification;
use App\Models\Shipment;
use App\Models\User;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Mail;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Spatie\Permission\Models\Role;

beforeEach(function (): void {
    Role::create(['name' => 'administrator']);
    Role::create(['name' => 'supervisor']);
});

it('imports a Rittal PBI spreadsheet using the alternate header mapping', function (): void {
    $admin = User::factory()->create();
    $admin->assignRole('administrator');

    $oldPickup = Location::factory()->pickup()->create(['short_code' => 'OLDP', 'name' => 'Old Pickup']);
    $oldDc = Location::factory()->distribution_center()->create(['short_code' => 'OLDD', 'name' => 'Old DC']);
    $newPickup = Location::factory()->pickup()->create(['short_code' => 'ING', 'name' => 'Ingrasys']);
    $newDc = Location::factory()->distribution_center()->create([
        'short_code' => 'AMS',
        'name' => 'AMS DC',
        'expected_arrival_time' => '08:00:00',
    ]);

    $shipment = Shipment::query()->create([
        'guid' => (string) str()->uuid(),
        'shipment_number' => 'LOAD-200',
        'status' => 'Pending',
        'po_number' => 'PO-100',
        'pickup_location_id' => $oldPickup->id,
        'dc_location_id' => $oldDc->id,
        'rack_qty' => 1,
        'load_bar_qty' => 1,
        'strap_qty' => 1,
    ]);

    $response = $this->actingAs($admin)
        ->from(route('admin.shipments.index'))
        ->post(route('admin.shipments.pbi-import'), [
            'file' => createPbiSpreadsheetUpload([
                ['Generated by Rittal Power BI'],
                ['Reporting period: March 2026'],
                ['Load', 'Status', 'Pro #', 'Order #', 'PickupRefNum', 'Origin', 'OriginAddress', 'OriginState', 'Destination', 'DestAddress', 'DestState', 'Sum of Pallets', 'Ship Date', 'Deliver Date', 'FETA'],
                ['LOAD-200', 'In Transit', 'PRO-9', 'PO-222', 'PICK-1', 'ING', '123 Origin St', 'TX', 'AMS', '456 Dest St', 'CA', 5, '3/26/2026', '3/27/2026', '3/27/2026'],
            ]),
        ]);

    $response->assertRedirect(route('admin.shipments.index'));
    $response->assertSessionHas('success', '0 new shipment(s) imported, 1 existing updated.');

    expect($shipment->fresh())
        ->status->toBe('In Transit')
        ->po_number->toBe('PO-222')
        ->pickup_location_id->toBe($newPickup->id)
        ->dc_location_id->toBe($newDc->id)
        ->rack_qty->toBe(5)
        ->load_bar_qty->toBe(2)
        ->strap_qty->toBe(13)
        ->pickup_date->toBeNull()
        ->delivery_date->toBeNull();

    expect($shipment->notes()->where('content', 'like', 'PBI import updated this shipment:%')->exists())->toBeTrue();
});

it('normalizes checked-in status from pbi import', function (): void {
    $admin = User::factory()->create();
    $admin->assignRole('administrator');

    $pickup = Location::factory()->pickup()->create(['short_code' => 'ING', 'name' => 'Ingrasys']);
    $dc = Location::factory()->distribution_center()->create(['short_code' => 'AMS', 'name' => 'AMS DC']);

    $shipment = Shipment::query()->create([
        'guid' => (string) str()->uuid(),
        'shipment_number' => 'LOAD-201',
        'status' => 'Pending',
        'pickup_location_id' => $pickup->id,
        'dc_location_id' => $dc->id,
    ]);

    $response = $this->actingAs($admin)
        ->from(route('admin.shipments.index'))
        ->post(route('admin.shipments.pbi-import'), [
            'file' => createPbiSpreadsheetUpload([
                ['Generated by Rittal Power BI'],
                ['Reporting period: March 2026'],
                ['Load', 'Status', 'Order #', 'Origin', 'Destination', 'Sum of Pallets', 'Ship Date'],
                ['LOAD-201', 'Checked-In', 'PO-201', 'ING', 'AMS', 1, '3/26/2026'],
            ]),
        ]);

    $response->assertRedirect(route('admin.shipments.index'));

    expect($shipment->fresh())
        ->status->toBe('Checked In');
});

it('does not change shipment dates from pbi import', function (): void {
    $admin = User::factory()->create();
    $admin->assignRole('administrator');

    $pickup = Location::factory()->pickup()->create(['short_code' => 'ING', 'name' => 'Ingrasys']);
    $dc = Location::factory()->distribution_center()->create(['short_code' => 'AMS', 'name' => 'AMS DC']);

    $shipment = Shipment::query()->create([
        'guid' => (string) str()->uuid(),
        'shipment_number' => 'LOAD-204',
        'status' => 'Pending',
        'pickup_location_id' => $pickup->id,
        'dc_location_id' => $dc->id,
        'drop_date' => '2026-03-25',
        'pickup_date' => '2026-03-26 08:00:00',
        'delivery_date' => '2026-03-27 08:00:00',
        'rack_qty' => 1,
    ]);

    $response = $this->actingAs($admin)
        ->from(route('admin.shipments.index'))
        ->post(route('admin.shipments.pbi-import'), [
            'file' => createPbiSpreadsheetUpload([
                ['Generated by Rittal Power BI'],
                ['Reporting period: March 2026'],
                ['Load', 'Status', 'Order #', 'Origin', 'Destination', 'Sum of Pallets', 'Ship Date', 'Deliver Date'],
                ['LOAD-204', 'Booked', 'PO-204', 'ING', 'AMS', 1, 'TBD', ''],
            ]),
        ]);

    $response->assertRedirect(route('admin.shipments.index'));

    expect($shipment->fresh())
        ->drop_date->toDateString()->toBe('2026-03-25')
        ->pickup_date->format('Y-m-d H:i:s')->toBe('2026-03-26 08:00:00')
        ->delivery_date->format('Y-m-d H:i:s')->toBe('2026-03-27 08:00:00');
});

it('maps elp rjs pickup to wiwynn rjs during pbi import', function (): void {
    $admin = User::factory()->create();
    $admin->assignRole('administrator');

    $mappedPickup = Location::factory()->pickup()->create(['short_code' => 'WIWYNN - RJS', 'name' => 'WIWYNN - RJS']);
    Location::factory()->pickup()->create(['short_code' => 'ELP-RJS', 'name' => 'Legacy ELP']);
    $dc = Location::factory()->distribution_center()->create(['short_code' => 'AMS', 'name' => 'AMS DC']);

    $shipment = Shipment::query()->create([
        'guid' => (string) str()->uuid(),
        'shipment_number' => 'LOAD-203',
        'status' => 'Pending',
        'pickup_location_id' => $dc->id,
        'dc_location_id' => $dc->id,
    ]);

    $response = $this->actingAs($admin)
        ->from(route('admin.shipments.index'))
        ->post(route('admin.shipments.pbi-import'), [
            'file' => createPbiSpreadsheetUpload([
                ['Generated by Rittal Power BI'],
                ['Reporting period: March 2026'],
                ['Load', 'Status', 'Order #', 'Origin', 'Destination', 'Sum of Pallets', 'Ship Date'],
                ['LOAD-203', 'Booked', 'PO-203', 'ELP-RJS', 'AMS', 1, '3/26/2026'],
            ]),
        ]);

    $response->assertRedirect(route('admin.shipments.index'));

    expect($shipment->fresh())
        ->pickup_location_id->toBe($mappedPickup->id)
        ->dc_location_id->toBe($dc->id);
});

it('skips pbi updates for fields previously changed by google sheets import notes', function (): void {
    $admin = User::factory()->create();
    $admin->assignRole('administrator');

    $pickup = Location::factory()->pickup()->create(['short_code' => 'ING', 'name' => 'Ingrasys']);
    $dc = Location::factory()->distribution_center()->create(['short_code' => 'AMS', 'name' => 'AMS DC']);

    $shipment = Shipment::query()->create([
        'guid' => (string) str()->uuid(),
        'shipment_number' => 'LOAD-202',
        'status' => 'Pending',
        'po_number' => 'PO-OLD',
        'pickup_location_id' => $pickup->id,
        'dc_location_id' => $dc->id,
        'rack_qty' => 1,
        'load_bar_qty' => 1,
        'strap_qty' => 1,
    ]);

    $shipment->notes()->create([
        'content' => "Google Sheets import updated this shipment:\nStatus changed from 'Booked' to 'Pending'",
        'is_admin' => false,
        'user_id' => $admin->id,
    ]);

    $response = $this->actingAs($admin)
        ->from(route('admin.shipments.index'))
        ->post(route('admin.shipments.pbi-import'), [
            'file' => createPbiSpreadsheetUpload([
                ['Generated by Rittal Power BI'],
                ['Reporting period: March 2026'],
                ['Load', 'Status', 'Order #', 'Origin', 'Destination', 'Sum of Pallets', 'Ship Date'],
                ['LOAD-202', 'In Transit', 'PO-NEW', 'ING', 'AMS', 1, '3/26/2026'],
            ]),
        ]);

    $response->assertRedirect(route('admin.shipments.index'));

    expect($shipment->fresh())
        ->status->toBe('Pending')
        ->po_number->toBe('PO-NEW');
});

function createPbiSpreadsheetUpload(array $rows): UploadedFile
{
    $spreadsheet = new Spreadsheet;
    $spreadsheet->getActiveSheet()->fromArray($rows, null, 'A1');

    $path = tempnam(sys_get_temp_dir(), 'pbi-import-');

    if ($path === false) {
        throw new RuntimeException('Failed to allocate a temporary file for the PBI import test.');
    }

    $writer = new Xlsx($spreadsheet);
    $writer->save($path);

    return new UploadedFile(
        $path,
        'rittal-pbi.xlsx',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        null,
        true,
    );
}

it('sends an import summary notification to all admins and supervisors after pbi import', function (): void {
    Mail::fake();

    $admin = User::factory()->create(['notification_email_enabled' => true]);
    $admin->assignRole('administrator');

    $supervisor = User::factory()->create(['notification_email_enabled' => true]);
    $supervisor->assignRole('supervisor');

    $unemailedAdmin = User::factory()->create(['notification_email_enabled' => false]);
    $unemailedAdmin->assignRole('administrator');

    $pickup = Location::factory()->pickup()->create(['short_code' => 'ING', 'name' => 'Ingrasys']);
    $dc = Location::factory()->distribution_center()->create([
        'short_code' => 'AMS',
        'name' => 'AMS DC',
        'expected_arrival_time' => '08:00:00',
    ]);

    $existingShipment = Shipment::query()->create([
        'guid' => (string) str()->uuid(),
        'shipment_number' => 'LOAD-PSUMM-001',
        'status' => 'Pending',
        'po_number' => 'PO-OLD',
        'pickup_location_id' => $pickup->id,
        'dc_location_id' => $dc->id,
        'rack_qty' => 1,
        'load_bar_qty' => 1,
        'strap_qty' => 1,
    ]);

    $response = $this->actingAs($admin)
        ->from(route('admin.shipments.index'))
        ->post(route('admin.shipments.pbi-import'), [
            'file' => createPbiSpreadsheetUpload([
                ['Generated by Rittal Power BI'],
                ['Reporting period: April 2026'],
                ['Load', 'Status', 'Order #', 'Origin', 'Destination', 'Sum of Pallets'],
                ['LOAD-PSUMM-001', 'In Transit', 'PO-NEW', 'ING', 'AMS', 3],
                ['LOAD-PSUMM-002', 'Booked', 'PO-NEW2', 'ING', 'AMS', 2],
            ]),
        ]);

    $response->assertRedirect(route('admin.shipments.index'));

    $summaryNotification = Notification::query()
        ->where('type', 'import_summary')
        ->latest('id')
        ->first();

    /** @var Notification $summaryNotification */
    expect($summaryNotification)->not->toBeNull();
    expect($summaryNotification->data['import_type'])->toBe('PBI');
    expect($summaryNotification->data['updated_count'])->toBe(1);
    expect($summaryNotification->data['created_count'])->toBe(1);
    expect($summaryNotification->data['importer_name'])->toBe($admin->name);
    expect($summaryNotification->data['updated_by_location'])->toHaveKey('Ingrasys', 1);
    expect($summaryNotification->data['created_by_location'])->toHaveKey('Ingrasys', 1);
    expect($summaryNotification->data['html_message'])->toContain('Ingrasys');

    expect($summaryNotification->users()->pluck('users.id')->all())
        ->toContain($admin->id)
        ->toContain($supervisor->id)
        ->toContain($unemailedAdmin->id);

    Mail::assertSent(ImportSummaryEmail::class, 2);
    Mail::assertSent(ImportSummaryEmail::class, fn (ImportSummaryEmail $mail) => $mail->hasTo($admin->email));
    Mail::assertSent(ImportSummaryEmail::class, fn (ImportSummaryEmail $mail) => $mail->hasTo($supervisor->email));
    Mail::assertNotSent(ImportSummaryEmail::class, fn (ImportSummaryEmail $mail) => $mail->hasTo($unemailedAdmin->email));
});

it('includes failed records in pbi import summary notification', function (): void {
    Mail::fake();

    $admin = User::factory()->create(['notification_email_enabled' => false]);
    $admin->assignRole('administrator');

    Location::factory()->pickup()->create(['short_code' => 'ING', 'name' => 'Ingrasys']);
    Location::factory()->distribution_center()->create([
        'short_code' => 'AMS',
        'name' => 'AMS DC',
        'expected_arrival_time' => '08:00:00',
    ]);

    $response = $this->actingAs($admin)
        ->from(route('admin.shipments.index'))
        ->post(route('admin.shipments.pbi-import'), [
            'file' => createPbiSpreadsheetUpload([
                ['Generated by Rittal Power BI'],
                ['Reporting period: April 2026'],
                ['Load', 'Status', 'Order #', 'Origin', 'Destination', 'Sum of Pallets'],
                ['LOAD-PFAIL-001', 'In Transit', 'PO-OK', 'ING', 'AMS', 2],
                ['LOAD-PFAIL-002', '', 'PO-BAD', 'ING', 'AMS', 2],
            ]),
        ]);

    $response->assertRedirect(route('admin.shipments.index'));

    $summaryNotification = Notification::query()
        ->where('type', 'import_summary')
        ->latest('id')
        ->first();

    /** @var Notification $summaryNotification */
    expect($summaryNotification)->not->toBeNull();
    expect($summaryNotification->data['created_count'])->toBe(1);
    expect($summaryNotification->data['failed_count'])->toBe(1);
    expect($summaryNotification->data['failed_details'])->toHaveCount(1);
    expect($summaryNotification->data['failed_details'][0])->toMatchArray([
        'shipment_number' => 'LOAD-PFAIL-002',
        'row_number' => 5,
        'sheet_name' => null,
    ]);
    expect($summaryNotification->data['html_message'])->toContain('Row 5');
});
